/**
 * Optimized Startup Script for BanaHosting (cPanel Node.js Selector)
 * This script leverages the 'standalone' output from Next.js for minimal RAM usage.
 */

// Set production environment
process.env.NODE_ENV = 'production';

// cPanel Node.js Selector passes the port via process.env.PORT
// We ensure it's set for the standalone server
const port = process.env.PORT || 3000;
process.env.PORT = port;

console.log(`[BanaHosting] Starting optimized standalone server on port ${port}...`);

// Require the standalone server generated by Next.js
// Path: .next/standalone/server.js
try {
  require('./.next/standalone/server.js');
} catch (error) {
  console.error('[CRITICAL_STARTUP_ERROR] Could not find standalone server.');
  console.error('Make sure you have run "npm run build" and uploaded the ".next/standalone" folder.');
  console.error(error);
  process.exit(1);
}
